/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2016-06-23 02:39:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.sys;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class PositionEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("it:formatDate", org.iweb.sys.DateUtil.class, "format", new Class[] {java.util.Date.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/iwebTag.tld", Long.valueOf(1466045442317L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005faction_0026_005fnamespace_005fname_005fexecuteResult_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fonsubmit_005fnamespace_005fname_005fmethod_005fid_005fcssClass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fhidden_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fcssClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fselect_0026_005ftitle_005fname_005flist_005fid_005fcssClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fselect_0026_005ftitle_005fname_005flistValue_005flistKey_005flist_005fid_005fheaderValue_005fheaderKey_005fcssClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fname_005fid_005fcssClass_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005felseif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fonclick_005fname_005fid_005fcssClass_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005faction_0026_005fnamespace_005fname_005fexecuteResult_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fonsubmit_005fnamespace_005fname_005fmethod_005fid_005fcssClass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fhidden_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fselect_0026_005ftitle_005fname_005flist_005fid_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fselect_0026_005ftitle_005fname_005flistValue_005flistKey_005flist_005fid_005fheaderValue_005fheaderKey_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fname_005fid_005fcssClass_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005felseif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fonclick_005fname_005fid_005fcssClass_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005faction_0026_005fnamespace_005fname_005fexecuteResult_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fonsubmit_005fnamespace_005fname_005fmethod_005fid_005fcssClass_005faction.release();
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005fhidden_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fcssClass_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fselect_0026_005ftitle_005fname_005flist_005fid_005fcssClass_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fselect_0026_005ftitle_005fname_005flistValue_005flistKey_005flist_005fid_005fheaderValue_005fheaderKey_005fcssClass_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fname_005fid_005fcssClass_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005felseif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fonclick_005fname_005fid_005fcssClass_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>用户列表--");
      if (_jspx_meth_s_005ftext_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      if (_jspx_meth_s_005faction_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_s_005faction_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<div class=\"tab_right\">\r\n");
      out.write("\t<div class=\"tab_warp main\">\r\n");
      out.write("\t\t<div class=\"dq_step\">\r\n");
      out.write("\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t<span class=\"opb lb op-area\"><a href=\"");
      if (_jspx_meth_s_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" >职务管理列表</a></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<input type=\"button\" value=\"新增kpi\" onClick=\"setkpi();\" />\r\n");
      out.write("\t\t");
      if (_jspx_meth_s_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      if (_jspx_meth_s_005faction_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_s_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){ \r\n");
      out.write("\tvar ajax = new Common_Ajax('message');\r\n");
      out.write("\tvar positionid=$(\"#positionid\").val();\r\n");
      out.write("\tajax.config.action_url = '");
      if (_jspx_meth_s_005furl_005f3(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\tajax.config._success = function(data, textStatus) {\r\n");
      out.write("\t\tvar arr=data;\r\n");
      out.write("\t\tvar show = new Array(); \r\n");
      out.write("\t\tvar dept_name=$(\"#position\\\\.position_name\").val();\r\n");
      out.write("\t\t$(\"[name='deletetd']\").remove();\r\n");
      out.write("\t\tfor (var i in arr) {  \r\n");
      out.write("\t\t\t show.push('<tr name=\"deletetd\" id=\"'+arr[i].uuid+'tr\">');\r\n");
      out.write("\t\t\t show.push('<td class=\"td1\"  >'+dept_name+'</td  >' ) ;\r\n");
      out.write("\t\t\t show.push('<td class=\"td2\"  id=\"'+arr[i].uuid+'kpi\">'+ arr[i].kpi+'</td  >' ) ;\r\n");
      out.write("\t\t\t show.push('<td class=\"td3\"  id=\"'+arr[i].uuid+'cyc\">'+ arr[i].cyc+'</td  >' ) ;\r\n");
      out.write("\t\t\t show.push('<td class=\"td4\"  id=\"'+arr[i].uuid+'weight\">'+ arr[i].weight+'</td  >' ) ;\r\n");
      out.write("\t\t\t show.push('<td class=\"td5\" id=\"'+arr[i].uuid+'count_way\">'+ arr[i].count_way+'</td  >' ) ;\r\n");
      out.write("\t\t\t show.push('<td class=\"td6\"  id=\"'+arr[i].uuid+'definition\">'+ arr[i].definition+'</td  >' ) ;\r\n");
      out.write("\t\t\t show.push('<td class=\"td7\" id=\"'+arr[i].uuid+'correctly\">'+ arr[i].correctly+'</td  >' ) ;\r\n");
      out.write("\t\t\t show.push('<td class=\"td5\" id=\"'+arr[i].uuid+'check_deptcode\">'+ arr[i].check_deptcode+'</td  >' ) ;\r\n");
      out.write("\t\t\t show.push('<td class=\"td6\" id=\"'+arr[i].uuid+'check_post\">'+ arr[i].check_post+'</td  >' ) ;\r\n");
      out.write("\t\t\t show.push('<td class=\"td7\" id=\"'+arr[i].uuid+'isdept\">'+ arr[i].isdept+'</td  >' ) ;\r\n");
      out.write("\t\t\t show.push(' <td class=\"td1 op-area\"><a  id=\"'+arr[i].uuid+'buttb\" onclick=\"javascript:updatetab('+arr[i].uuid+')\" href=\"javascript:void(0)\" class=\"input-red\">修改</a><a style=\"display: none\" id=\"'+arr[i].uuid+'buttd\" onclick=\"javascript:updatedetermine('+arr[i].uuid+')\" href=\"javascript:void(0)\" class=\"input-greed\">保存</a></td>') ;\r\n");
      out.write("\t\t\t show.push('</tr>');\r\n");
      out.write("\t\t\t}  \r\n");
      out.write("\t\t $(\"#intop\").append(show.join(\"\"));\r\n");
      out.write("\t};\r\n");
      out.write("\tajax.addParameter(\"privilege_id\", \"SYS_MANAGER_DEPT_LOADKPI\");\r\n");
      out.write("\tajax.addParameter(\"parameters\", \"positionid=\" + positionid);\r\n");
      out.write("\tajax.sendAjax();\r\n");
      out.write("});\r\n");
      out.write("function updatedetermine(obj){\r\n");
      out.write("\tvar positionid=$(\"#positionid\").val();\r\n");
      out.write("\tvar ajax = new Common_Ajax('message');\r\n");
      out.write("\tvar kpi=$(\"#\"+obj+\"kpiip\").val();\r\n");
      out.write("\t var weight=$(\"#\"+obj+\"weightip\").val();\r\n");
      out.write("\t var cyc=$(\"#\"+obj+\"cyc\").val();\r\n");
      out.write("\t var count_way=$(\"#\"+obj+\"count_wayip\").val();\r\n");
      out.write("\t var definition=$(\"#\"+obj+\"definitionip\").val();\r\n");
      out.write("\t var correctly=$(\"#\"+obj+\"correctlyip\").val();\r\n");
      out.write("\t var check_deptcode=$(\"#\"+obj+\"check_deptcodeip\").val();\r\n");
      out.write("\t var check_post=$(\"#\"+obj+\"check_postip\").val();\r\n");
      out.write("\t var isdept=$(\"#\"+obj+\"isdeptip\").val();\r\n");
      out.write("\tajax.config.action_url = '");
      if (_jspx_meth_s_005furl_005f4(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\tajax.config._success = function(data, textStatus) {\r\n");
      out.write("\t\tvar show = new Array(); \r\n");
      out.write("\t\tvar dept_name=$(\"#position\\\\.position_name\").val();\r\n");
      out.write("\t\t show.push('<td class=\"td1\">'+dept_name+'</td  >' ) ;\r\n");
      out.write("\t\t show.push('<td class=\"td2\"  id=\"'+obj+'kpi\">'+kpi+'</td  >' ) ;\r\n");
      out.write("\t\t show.push('<td class=\"td3\"  id=\"'+obj+'cyc\">'+ cyc+'</td  >' ) ;\r\n");
      out.write("\t\t show.push('<td class=\"td4\"  id=\"'+obj+'weight\">'+weight+'</td  >' ) ;\r\n");
      out.write("\t\t show.push('<td class=\"td5\" id=\"'+obj+'count_way\">'+count_way+'</td  >' ) ;\r\n");
      out.write("\t\t show.push('<td class=\"td6\"  id=\"'+obj+'definition\">'+ definition+'</td  >' ) ;\r\n");
      out.write("\t\t show.push('<td class=\"td7\" id=\"'+obj+'correctly\">'+correctly+'</td  >' ) ;\r\n");
      out.write("\t\t show.push('<td class=\"td5\" id=\"'+obj+'check_deptcode\">'+check_deptcode+'</td  >' ) ;\r\n");
      out.write("\t\t show.push('<td class=\"td6\" id=\"'+obj+'check_post\">'+ check_post+'</td  >' ) ;\r\n");
      out.write("\t\t show.push('<td class=\"td7\" id=\"'+obj+'isdept\">'+isdept+'</td  >' ) ;\r\n");
      out.write("\t\t show.push(' <td class=\"td1 op-area\"><a  id=\"'+obj+'buttb\" onclick=\"javascript:updatetab('+obj+')\" href=\"javascript:void(0)\" class=\"input-red\">修改</a><a style=\"display: none\" id=\"'+obj+'buttd\" onclick=\"javascript:updatedetermine('+obj+')\" href=\"javascript:void(0)\" class=\"input-greed\">保存</a></td>') ;\r\n");
      out.write("\t\t $(\"#\"+obj+\"tr\").empty();\t\r\n");
      out.write("\t\t $(\"#\"+obj+\"tr\").append(show.join(\"\"));\r\n");
      out.write("\t};\r\n");
      out.write("\tajax.addParameter(\"privilege_id\", \"SYS_MANAGER_DEPT_UPDATEKPI\");\r\n");
      out.write("\tajax.addParameter(\"work\",\"update\");\r\n");
      out.write("\tajax.addParameter(\"parameters\", \"dept_code=\" + obj+\"&kpi=\"+encodeURI(kpi)+\"&weight=\"+weight+\"&count_way=\"+count_way\r\n");
      out.write("\t\t\t+\"&definition=\"+definition+\"&correctly=\"+correctly+\"&check_deptcode=\"+check_deptcode+\"&check_post=\"+check_post\r\n");
      out.write("\t\t\t+\"&isdept=\"+isdept);\r\n");
      out.write("\tajax.sendAjax();\r\n");
      out.write("}\r\n");
      out.write("function updatetab(obj) {\r\n");
      out.write("\r\n");
      out.write("\tvar show = new Array(); \r\n");
      out.write("\tvar kpi=$(\"#\"+obj+\"kpi\").text();\r\n");
      out.write("\t show.push('<input type=\"text\" value=\"'+kpi+'\" id=\"'+obj+'kpiip\" />');\r\n");
      out.write("\t $(\"#\"+obj+\"kpi\").text(\"\");\r\n");
      out.write("\t $(\"#\"+obj+\"kpi\").append(show.join(\"\"));\r\n");
      out.write("\t show=[];\r\n");
      out.write("\t var weight=$(\"#\"+obj+\"weight\").text();\r\n");
      out.write("\t show.push('<input type=\"text\" value=\"'+weight+'\" id=\"'+obj+'weightip\" />');\r\n");
      out.write("\t $(\"#\"+obj+\"weight\").text(\"\");\r\n");
      out.write("\t $(\"#\"+obj+\"weight\").append(show.join(\"\"));\r\n");
      out.write("\t show=[];\r\n");
      out.write("\t var count_way=$(\"#\"+obj+\"count_way\").text();\r\n");
      out.write("\t show.push('<input type=\"text\" style=\"width:80px\" value=\"'+count_way+'\" id=\"'+obj+'count_wayip\" />');\r\n");
      out.write("\t $(\"#\"+obj+\"count_way\").text(\"\");\r\n");
      out.write("\t $(\"#\"+obj+\"count_way\").append(show.join(\"\"));\r\n");
      out.write("\t show=[];\r\n");
      out.write("\t var definition=$(\"#\"+obj+\"definition\").text();\r\n");
      out.write("\t show.push('<input type=\"text\" style=\"width:80px\" value=\"'+definition+'\" id=\"'+obj+'definitionip\" />');\r\n");
      out.write("\t $(\"#\"+obj+\"definition\").text(\"\");\r\n");
      out.write("\t $(\"#\"+obj+\"definition\").append(show.join(\"\"));\r\n");
      out.write("\t show=[];\r\n");
      out.write("\t var correctly=$(\"#\"+obj+\"correctly\").text();\r\n");
      out.write("\t show.push('<input type=\"text\" style=\"width:80px\" value=\"'+correctly+'\" id=\"'+obj+'correctlyip\" />');\r\n");
      out.write("\t $(\"#\"+obj+\"correctly\").text(\"\");\r\n");
      out.write("\t $(\"#\"+obj+\"correctly\").append(show.join(\"\"));\r\n");
      out.write("\t show=[];\r\n");
      out.write("\t var check_deptcode=$(\"#\"+obj+\"check_deptcode\").text();\r\n");
      out.write("\t show.push('<input type=\"text\" style=\"width:80px\" value=\"'+check_deptcode+'\" id=\"'+obj+'check_deptcodeip\" />');\r\n");
      out.write("\t $(\"#\"+obj+\"check_deptcode\").text(\"\");\r\n");
      out.write("\t $(\"#\"+obj+\"check_deptcode\").append(show.join(\"\"));\r\n");
      out.write("\t show=[];\r\n");
      out.write("\t var check_post=$(\"#\"+obj+\"check_post\").text();\r\n");
      out.write("\t show.push('<input type=\"text\" style=\"width:80px\" value=\"'+check_post+'\" id=\"'+obj+'check_postip\" />');\r\n");
      out.write("\t $(\"#\"+obj+\"check_post\").text(\"\");\r\n");
      out.write("\t $(\"#\"+obj+\"check_post\").append(show.join(\"\"));\r\n");
      out.write("\t show=[];\r\n");
      out.write("\t var isdept=$(\"#\"+obj+\"isdept\").text();\r\n");
      out.write("\t show.push('<input type=\"text\" style=\"width:80px\" value=\"'+isdept+'\" id=\"'+obj+'isdeptip\" />');\r\n");
      out.write("\t $(\"#\"+obj+\"isdept\").text(\"\");\r\n");
      out.write("\t $(\"#\"+obj+\"isdept\").append(show.join(\"\"));\r\n");
      out.write("\t show=[];\r\n");
      out.write("\t $(\"#\"+obj+\"buttd\").show()\r\n");
      out.write("\t  $(\"#\"+obj+\"buttb\").hide()\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setkpi() {\r\n");
      out.write("\r\n");
      out.write("\tvar dept_name=$(\"#position\\\\.position_name\").val();\r\n");
      out.write("\r\n");
      out.write("\tvar show = new Array(); \r\n");
      out.write("\t show.push('<tr name=\"deletetd\" ·>');\r\n");
      out.write("\t show.push('<td class=\"td1\"  >'+dept_name+'</td  >' ) ;\r\n");
      out.write("\t show.push('<td class=\"td2\" ><input type=\"text\" value=\"\" id=\"newkpiip\" /></td  >' ) ;\r\n");
      out.write("\t show.push('<td class=\"td5\">1</td  >' ) ;\r\n");
      out.write("\t show.push('<td class=\"td3\" ><input type=\"text\" value=\"\" id=\"newweightip\" /></td  >' ) ;\r\n");
      out.write("\t show.push('<td class=\"td4\" ><input type=\"text\" style=\"width:80px\" value=\"\" id=\"newcount_wayip\" /></td  >' ) ;\r\n");
      out.write("\t show.push('<td class=\"td6\"  ><input type=\"text\" style=\"width:80px\" value=\"\" id=\"newdefinitionip\" /></td  >' ) ;\r\n");
      out.write("\t show.push('<td class=\"td7\"><input type=\"text\" style=\"width:80px\" value=\"\" id=\"newcorrectlyip\" /></td  >' ) ;\r\n");
      out.write("\t show.push('<td class=\"td5\"><input type=\"text\" style=\"width:80px\" value=\"\" id=\"newcheck_deptcodeip\" /></td  >' ) ;\r\n");
      out.write("\t show.push('<td class=\"td6\" ><input type=\"text\" style=\"width:80px\" value=\"\" id=\"newcheck_postip\" /></td  >' ) ;\r\n");
      out.write("\t show.push('<td class=\"td7\" ><input type=\"text\" style=\"width:80px\" value=\"\" id=\"newisdeptip\" /></td  >' ) ;\r\n");
      out.write("\t show.push(' <td class=\"td1 op-area\"><a   onclick=\"javascript:addtab()\" href=\"javascript:void(0)\" class=\"input-greed\">添加</a></td>') ;\r\n");
      out.write("\t show.push('</tr>');\r\n");
      out.write("\t $(\"#intop\").append(show.join(\"\"));\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function addtab(ct) {\r\n");
      out.write("\tvar positionid=$(\"#positionid\").val();\r\n");
      out.write("\r\n");
      out.write("\tvar ajax = new Common_Ajax('message');\r\n");
      out.write("\tvar kpi=$(\"#newkpiip\").val();\r\n");
      out.write("\tvar weight=$(\"#newweightip\").val();\r\n");
      out.write("\tvar count_way=$(\"#newcount_wayip\").val();\r\n");
      out.write("\tvar definition=$(\"#newdefinitionip\").val();\r\n");
      out.write("\tvar correctly=$(\"#newcorrectlyip\").val();\r\n");
      out.write("\tvar check_deptcode=$(\"#newcheck_deptcodeip\").val();\r\n");
      out.write("\tvar check_post=$(\"#newcheck_postip\").val();\r\n");
      out.write("\tvar isdept=$(\"#newisdeptip\").val();\r\n");
      out.write("\tvar dept_code=$(\"#dept\\\\.dept_code\").val();\r\n");
      out.write("\tajax.config.action_url = '");
      if (_jspx_meth_s_005furl_005f5(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\tajax.config._success = function(data, textStatus) {\r\n");
      out.write("\t\t  window.location.reload();//刷新当前页面.\r\n");
      out.write("\t};\r\n");
      out.write("\tajax.addParameter(\"privilege_id\", \"SYS_MANAGER_DEPT_ADDKPI\");\r\n");
      out.write("\tajax.addParameter(\"work\",\"update\");\r\n");
      out.write("\tajax.addParameter(\"parameters\", \"positionid=\" + positionid+\"&kpi=\"+encodeURI(kpi)+\"&weight=\"+weight+\"&count_way=\"+count_way\r\n");
      out.write("\t\t\t+\"&definition=\"+definition+\"&correctly=\"+correctly+\"&check_deptcode=\"+check_deptcode+\"&check_post=\"+check_post\r\n");
      out.write("\t\t\t+\"&isdept=\"+isdept+\"&type=2\");\r\n");
      out.write("\tajax.sendAjax();\r\n");
      out.write("}\r\n");
      out.write("\t//type=2是部门权重 type=1是职务权重\r\n");
      out.write("\t \r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005ftext_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f0 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    _jspx_th_s_005ftext_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftext_005f0.setParent(null);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(8,13) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftext_005f0.setName("APP_NAME");
    int _jspx_eval_s_005ftext_005f0 = _jspx_th_s_005ftext_005f0.doStartTag();
    if (_jspx_th_s_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005faction_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:action
    org.apache.struts2.views.jsp.ActionTag _jspx_th_s_005faction_005f0 = (org.apache.struts2.views.jsp.ActionTag) _005fjspx_005ftagPool_005fs_005faction_0026_005fnamespace_005fname_005fexecuteResult_005fnobody.get(org.apache.struts2.views.jsp.ActionTag.class);
    _jspx_th_s_005faction_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005faction_005f0.setParent(null);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(9,0) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005faction_005f0.setName("ref_head");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(9,0) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005faction_005f0.setNamespace("/manager");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(9,0) name = executeResult type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005faction_005f0.setExecuteResult(true);
    int _jspx_eval_s_005faction_005f0 = _jspx_th_s_005faction_005f0.doStartTag();
    if (_jspx_th_s_005faction_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005faction_0026_005fnamespace_005fname_005fexecuteResult_005fnobody.reuse(_jspx_th_s_005faction_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005faction_0026_005fnamespace_005fname_005fexecuteResult_005fnobody.reuse(_jspx_th_s_005faction_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005faction_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:action
    org.apache.struts2.views.jsp.ActionTag _jspx_th_s_005faction_005f1 = (org.apache.struts2.views.jsp.ActionTag) _005fjspx_005ftagPool_005fs_005faction_0026_005fnamespace_005fname_005fexecuteResult_005fnobody.get(org.apache.struts2.views.jsp.ActionTag.class);
    _jspx_th_s_005faction_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005faction_005f1.setParent(null);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(12,0) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005faction_005f1.setName("nav");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(12,0) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005faction_005f1.setNamespace("/manage");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(12,0) name = executeResult type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005faction_005f1.setExecuteResult(true);
    int _jspx_eval_s_005faction_005f1 = _jspx_th_s_005faction_005f1.doStartTag();
    if (_jspx_th_s_005faction_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005faction_0026_005fnamespace_005fname_005fexecuteResult_005fnobody.reuse(_jspx_th_s_005faction_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005faction_0026_005fnamespace_005fname_005fexecuteResult_005fnobody.reuse(_jspx_th_s_005faction_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f0 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f0.setParent(null);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(17,41) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f0.setNamespace("/sys");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(17,41) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f0.setAction("position_list");
    int _jspx_eval_s_005furl_005f0 = _jspx_th_s_005furl_005f0.doStartTag();
    if (_jspx_th_s_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:form
    org.apache.struts2.views.jsp.ui.FormTag _jspx_th_s_005fform_005f0 = (org.apache.struts2.views.jsp.ui.FormTag) _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fonsubmit_005fnamespace_005fname_005fmethod_005fid_005fcssClass_005faction.get(org.apache.struts2.views.jsp.ui.FormTag.class);
    _jspx_th_s_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fform_005f0.setParent(null);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(20,2) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setId("formEdit");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(20,2) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setName("form1");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(20,2) name = cssClass type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setCssClass("validForm");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(20,2) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setAction("position_add");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(20,2) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setNamespace("/sys");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(20,2) name = onsubmit type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setOnsubmit("return validator(this);");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(20,2) name = method type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setMethod("post");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(20,2) name = theme type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setTheme("simple");
    int _jspx_eval_s_005fform_005f0 = _jspx_th_s_005fform_005f0.doStartTag();
    if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fform_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fform_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\r\n");
        out.write("\t\t\t");
        if (_jspx_meth_s_005fif_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t<div class=\"label_hang clear\">\r\n");
        out.write("\t\t       <div class=\"label_ltit\">职务名称:</div>\r\n");
        out.write("\t\t       <div class=\"label_rwben\">");
        if (_jspx_meth_s_005ftextfield_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("</div>\r\n");
        out.write("\t\t\t</div>\r\n");
        out.write("\t\t\t<div class=\"label_hang\">\r\n");
        out.write("\t\t       <div class=\"label_ltit\">职务级别:</div>\r\n");
        out.write("\t\t       <div class=\"label_rwben\">");
        if (_jspx_meth_s_005fselect_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("</div>\r\n");
        out.write("\t\t\t</div>\r\n");
        out.write("\t\t\t<div class=\"label_hang\">\r\n");
        out.write("\t\t       <div class=\"label_ltit\">汇报对象:</div>\r\n");
        out.write("\t\t       <div class=\"label_rwbenx\">");
        if (_jspx_meth_s_005fselect_005f1(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("</div>\r\n");
        out.write("\t\t\t</div>\r\n");
        out.write("\t\t\t<div class=\"label_hang\">\r\n");
        out.write("\t\t       <div class=\"label_ltit\">职务属性:</div>\r\n");
        out.write("\t\t       <div class=\"label_rwben\">");
        if (_jspx_meth_s_005ftextfield_005f1(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("</div>\r\n");
        out.write("\t\t\t</div>\r\n");
        out.write("\t\t\t<div class=\"label_hang clear\">\r\n");
        out.write("\t\t       <div class=\"label_ltit\">职务描述:</div>\r\n");
        out.write("\t\t       <div class=\"label_rwben\">");
        if (_jspx_meth_s_005ftextfield_005f2(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("</div>\r\n");
        out.write("\t\t\t</div>\r\n");
        out.write("\t\t\t");
        if (_jspx_meth_s_005fif_005f1(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\t\t<div class=\"tab_warp\">\r\n");
        out.write("\t\t\t\t       <table  id=\"intop\">\r\n");
        out.write("\t\t<tr>\r\n");
        out.write("\t\t<th class=\"td1\" >职务名称</th  >\r\n");
        out.write("\t\t<th class=\"td3\" >kpi</th  >\r\n");
        out.write("\t\t <th class=\"td3\" >周期</th  >\r\n");
        out.write("\t\t<th class=\"td4\" >权重</th  >\r\n");
        out.write("\t\t<th class=\"td5\" >计分方式</th  >\r\n");
        out.write("\t\t<th class=\"td6\" >指标定义</th >\r\n");
        out.write("\t\t<th class=\"td7\" >指标标准</th >\r\n");
        out.write("\t\t <th class=\"td5\" >横向考核部门 </th  >\r\n");
        out.write("\t\t <th class=\"td6\" >横向考核岗位</th  >\r\n");
        out.write("\t\t <th class=\"td7\" >取部门得分</th  >\r\n");
        out.write("\t\t  <th class=\"td8\" >操作</th  >\r\n");
        out.write("\t\t</tr>\r\n");
        out.write("\t\t</table>\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\t\t\t<div class=\"label_hang clear\">\r\n");
        out.write("\t\t       <div class=\"label_ltit\">相关操作:</div>\r\n");
        out.write("\t\t       <div class=\"label_rwbenx\">\r\n");
        out.write("\t\t       \t\t");
        if (_jspx_meth_s_005fif_005f2(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_s_005felseif_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t<input type=\"button\" value=\"返回\" onclick=\"linkurl('");
        if (_jspx_meth_s_005furl_005f1(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("');\" class=\"input-gray\"/>\r\n");
        out.write("\t\t\t\t\t<span id=\"message\">");
        if (_jspx_meth_s_005fproperty_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("</span>\r\n");
        out.write("\t\t       </div>\r\n");
        out.write("\t\t\t</div>\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_s_005fform_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fonsubmit_005fnamespace_005fname_005fmethod_005fid_005fcssClass_005faction.reuse(_jspx_th_s_005fform_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fonsubmit_005fnamespace_005fname_005fmethod_005fid_005fcssClass_005faction.reuse(_jspx_th_s_005fform_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(22,3) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fif_005f0.setTest("null != position");
    int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
    if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fif_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fif_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t\t<div class=\"label_hang\">\r\n");
        out.write("\t\t\t       <div class=\"label_ltit\">用户ID:</div>\r\n");
        out.write("\t\t\t       <div class=\"label_rwbenx\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${position.uuid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        if (_jspx_meth_s_005fhidden_005f0(_jspx_th_s_005fif_005f0, _jspx_page_context))
          return true;
        out.write("</div>\r\n");
        out.write("\t\t\t       <input type=\"hidden\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${position.uuid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" id=\"positionid\"></input>\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fhidden_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:hidden
    org.apache.struts2.views.jsp.ui.HiddenTag _jspx_th_s_005fhidden_005f0 = (org.apache.struts2.views.jsp.ui.HiddenTag) _005fjspx_005ftagPool_005fs_005fhidden_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.ui.HiddenTag.class);
    _jspx_th_s_005fhidden_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fhidden_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(25,52) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fhidden_005f0.setName("position.uuid");
    int _jspx_eval_s_005fhidden_005f0 = _jspx_th_s_005fhidden_005f0.doStartTag();
    if (_jspx_th_s_005fhidden_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fhidden_0026_005fname_005fnobody.reuse(_jspx_th_s_005fhidden_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fhidden_0026_005fname_005fnobody.reuse(_jspx_th_s_005fhidden_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005ftextfield_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textfield
    org.apache.struts2.views.jsp.ui.TextFieldTag _jspx_th_s_005ftextfield_005f0 = (org.apache.struts2.views.jsp.ui.TextFieldTag) _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fcssClass_005fnobody.get(org.apache.struts2.views.jsp.ui.TextFieldTag.class);
    _jspx_th_s_005ftextfield_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftextfield_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(31,34) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f0.setId("position.position_name");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(31,34) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f0.setName("position.position_name");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(31,34) name = title type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f0.setTitle("职务名称");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(31,34) name = cssClass type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f0.setCssClass("validate[required]");
    int _jspx_eval_s_005ftextfield_005f0 = _jspx_th_s_005ftextfield_005f0.doStartTag();
    if (_jspx_th_s_005ftextfield_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fcssClass_005fnobody.reuse(_jspx_th_s_005ftextfield_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fcssClass_005fnobody.reuse(_jspx_th_s_005ftextfield_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fselect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:select
    org.apache.struts2.views.jsp.ui.SelectTag _jspx_th_s_005fselect_005f0 = (org.apache.struts2.views.jsp.ui.SelectTag) _005fjspx_005ftagPool_005fs_005fselect_0026_005ftitle_005fname_005flist_005fid_005fcssClass_005fnobody.get(org.apache.struts2.views.jsp.ui.SelectTag.class);
    _jspx_th_s_005fselect_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(35,34) name = title type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setTitle("职务级别");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(35,34) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setId("position.position_grade");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(35,34) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setName("position.position_grade");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(35,34) name = list type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setList("#{1:'总经理',2:'副总经理',3:'总监',4:'经理',5:'主管',6:'员工'}");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(35,34) name = cssClass type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setCssClass("validate[required]");
    int _jspx_eval_s_005fselect_005f0 = _jspx_th_s_005fselect_005f0.doStartTag();
    if (_jspx_th_s_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fselect_0026_005ftitle_005fname_005flist_005fid_005fcssClass_005fnobody.reuse(_jspx_th_s_005fselect_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fselect_0026_005ftitle_005fname_005flist_005fid_005fcssClass_005fnobody.reuse(_jspx_th_s_005fselect_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fselect_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:select
    org.apache.struts2.views.jsp.ui.SelectTag _jspx_th_s_005fselect_005f1 = (org.apache.struts2.views.jsp.ui.SelectTag) _005fjspx_005ftagPool_005fs_005fselect_0026_005ftitle_005fname_005flistValue_005flistKey_005flist_005fid_005fheaderValue_005fheaderKey_005fcssClass_005fnobody.get(org.apache.struts2.views.jsp.ui.SelectTag.class);
    _jspx_th_s_005fselect_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fselect_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(39,35) name = title type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f1.setTitle("汇报对象");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(39,35) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f1.setId("position.position_senior");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(39,35) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f1.setName("position.position_senior");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(39,35) name = list type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f1.setList("positions");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(39,35) name = listKey type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f1.setListKey("uuid");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(39,35) name = listValue type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f1.setListValue("position_name");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(39,35) name = headerKey type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f1.setHeaderKey("0");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(39,35) name = headerValue type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f1.setHeaderValue("无");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(39,35) name = cssClass type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f1.setCssClass("validate[required]");
    int _jspx_eval_s_005fselect_005f1 = _jspx_th_s_005fselect_005f1.doStartTag();
    if (_jspx_th_s_005fselect_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fselect_0026_005ftitle_005fname_005flistValue_005flistKey_005flist_005fid_005fheaderValue_005fheaderKey_005fcssClass_005fnobody.reuse(_jspx_th_s_005fselect_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fselect_0026_005ftitle_005fname_005flistValue_005flistKey_005flist_005fid_005fheaderValue_005fheaderKey_005fcssClass_005fnobody.reuse(_jspx_th_s_005fselect_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005ftextfield_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textfield
    org.apache.struts2.views.jsp.ui.TextFieldTag _jspx_th_s_005ftextfield_005f1 = (org.apache.struts2.views.jsp.ui.TextFieldTag) _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fnobody.get(org.apache.struts2.views.jsp.ui.TextFieldTag.class);
    _jspx_th_s_005ftextfield_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftextfield_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(43,34) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f1.setId("position.position_attribute");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(43,34) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f1.setName("position.position_attribute");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(43,34) name = title type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f1.setTitle("职务属性");
    int _jspx_eval_s_005ftextfield_005f1 = _jspx_th_s_005ftextfield_005f1.doStartTag();
    if (_jspx_th_s_005ftextfield_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fnobody.reuse(_jspx_th_s_005ftextfield_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fnobody.reuse(_jspx_th_s_005ftextfield_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005ftextfield_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textfield
    org.apache.struts2.views.jsp.ui.TextFieldTag _jspx_th_s_005ftextfield_005f2 = (org.apache.struts2.views.jsp.ui.TextFieldTag) _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fcssClass_005fnobody.get(org.apache.struts2.views.jsp.ui.TextFieldTag.class);
    _jspx_th_s_005ftextfield_005f2.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftextfield_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(47,34) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f2.setId("position.position_note");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(47,34) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f2.setName("position.position_note");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(47,34) name = title type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f2.setTitle("职务描述");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(47,34) name = cssClass type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f2.setCssClass("label_hang_linput");
    int _jspx_eval_s_005ftextfield_005f2 = _jspx_th_s_005ftextfield_005f2.doStartTag();
    if (_jspx_th_s_005ftextfield_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fcssClass_005fnobody.reuse(_jspx_th_s_005ftextfield_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005ftitle_005fname_005fid_005fcssClass_005fnobody.reuse(_jspx_th_s_005ftextfield_005f2);
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f1 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    _jspx_th_s_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(49,3) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fif_005f1.setTest("null != position");
    int _jspx_eval_s_005fif_005f1 = _jspx_th_s_005fif_005f1.doStartTag();
    if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fif_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fif_005f1.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t\t<div class=\"label_hang clear\">\r\n");
        out.write("\t\t\t       <div class=\"label_ltit\">修改人:</div>\r\n");
        out.write("\t\t\t       <div class=\"label_rwben\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${position.lm_user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        if (_jspx_meth_s_005fhidden_005f1(_jspx_th_s_005fif_005f1, _jspx_page_context))
          return true;
        out.write("</div>\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t<div class=\"label_hang\">\r\n");
        out.write("\t\t\t       <div class=\"label_ltit\">修改时间:</div>\r\n");
        out.write("\t\t\t       <div class=\"label_rwbenx\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${it:formatDate(position.lm_time,'yyyy-MM-dd HH:mm:ss')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
        out.write("</div>\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_s_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fhidden_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:hidden
    org.apache.struts2.views.jsp.ui.HiddenTag _jspx_th_s_005fhidden_005f1 = (org.apache.struts2.views.jsp.ui.HiddenTag) _005fjspx_005ftagPool_005fs_005fhidden_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.ui.HiddenTag.class);
    _jspx_th_s_005fhidden_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fhidden_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f1);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(52,54) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fhidden_005f1.setName("position.lm_user");
    int _jspx_eval_s_005fhidden_005f1 = _jspx_th_s_005fhidden_005f1.doStartTag();
    if (_jspx_th_s_005fhidden_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fhidden_0026_005fname_005fnobody.reuse(_jspx_th_s_005fhidden_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fhidden_0026_005fname_005fnobody.reuse(_jspx_th_s_005fhidden_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f2 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    _jspx_th_s_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_s_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(82,11) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fif_005f2.setTest("null == position && 'add' == viewFlag");
    int _jspx_eval_s_005fif_005f2 = _jspx_th_s_005fif_005f2.doStartTag();
    if (_jspx_eval_s_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fif_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fif_005f2.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fif_005f2.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        if (_jspx_meth_s_005fsubmit_005f0(_jspx_th_s_005fif_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_s_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fif_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_s_005fsubmit_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:submit
    org.apache.struts2.views.jsp.ui.SubmitTag _jspx_th_s_005fsubmit_005f0 = (org.apache.struts2.views.jsp.ui.SubmitTag) _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fname_005fid_005fcssClass_005faction_005fnobody.get(org.apache.struts2.views.jsp.ui.SubmitTag.class);
    _jspx_th_s_005fsubmit_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fsubmit_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f2);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(83,6) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f0.setId("add");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(83,6) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f0.setName("add");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(83,6) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f0.setValue("增加");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(83,6) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f0.setAction("position_add");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(83,6) name = cssClass type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f0.setCssClass("input-blue");
    int _jspx_eval_s_005fsubmit_005f0 = _jspx_th_s_005fsubmit_005f0.doStartTag();
    if (_jspx_th_s_005fsubmit_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fname_005fid_005fcssClass_005faction_005fnobody.reuse(_jspx_th_s_005fsubmit_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fname_005fid_005fcssClass_005faction_005fnobody.reuse(_jspx_th_s_005fsubmit_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005felseif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:elseif
    org.apache.struts2.views.jsp.ElseIfTag _jspx_th_s_005felseif_005f0 = (org.apache.struts2.views.jsp.ElseIfTag) _005fjspx_005ftagPool_005fs_005felseif_0026_005ftest.get(org.apache.struts2.views.jsp.ElseIfTag.class);
    _jspx_th_s_005felseif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005felseif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(85,5) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005felseif_005f0.setTest("null != position && 'mdy' == viewFlag");
    int _jspx_eval_s_005felseif_005f0 = _jspx_th_s_005felseif_005f0.doStartTag();
    if (_jspx_eval_s_005felseif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005felseif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005felseif_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005felseif_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        if (_jspx_meth_s_005fsubmit_005f1(_jspx_th_s_005felseif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        if (_jspx_meth_s_005fsubmit_005f2(_jspx_th_s_005felseif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_s_005felseif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005felseif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005felseif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005felseif_0026_005ftest.reuse(_jspx_th_s_005felseif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005felseif_0026_005ftest.reuse(_jspx_th_s_005felseif_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fsubmit_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005felseif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:submit
    org.apache.struts2.views.jsp.ui.SubmitTag _jspx_th_s_005fsubmit_005f1 = (org.apache.struts2.views.jsp.ui.SubmitTag) _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fname_005fid_005fcssClass_005faction_005fnobody.get(org.apache.struts2.views.jsp.ui.SubmitTag.class);
    _jspx_th_s_005fsubmit_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fsubmit_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005felseif_005f0);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(86,6) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f1.setId("save");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(86,6) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f1.setName("save");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(86,6) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f1.setValue("保存");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(86,6) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f1.setAction("position_save");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(86,6) name = cssClass type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f1.setCssClass("input-blue");
    int _jspx_eval_s_005fsubmit_005f1 = _jspx_th_s_005fsubmit_005f1.doStartTag();
    if (_jspx_th_s_005fsubmit_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fname_005fid_005fcssClass_005faction_005fnobody.reuse(_jspx_th_s_005fsubmit_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fname_005fid_005fcssClass_005faction_005fnobody.reuse(_jspx_th_s_005fsubmit_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fsubmit_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005felseif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:submit
    org.apache.struts2.views.jsp.ui.SubmitTag _jspx_th_s_005fsubmit_005f2 = (org.apache.struts2.views.jsp.ui.SubmitTag) _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fonclick_005fname_005fid_005fcssClass_005faction_005fnobody.get(org.apache.struts2.views.jsp.ui.SubmitTag.class);
    _jspx_th_s_005fsubmit_005f2.setPageContext(_jspx_page_context);
    _jspx_th_s_005fsubmit_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005felseif_005f0);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(87,6) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f2.setId("delete");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(87,6) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f2.setName("delete");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(87,6) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f2.setValue("删除");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(87,6) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f2.setAction("position_del");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(87,6) name = onclick type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f2.setOnclick("return isDel();");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(87,6) name = cssClass type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f2.setCssClass("input-red");
    int _jspx_eval_s_005fsubmit_005f2 = _jspx_th_s_005fsubmit_005f2.doStartTag();
    if (_jspx_th_s_005fsubmit_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fonclick_005fname_005fid_005fcssClass_005faction_005fnobody.reuse(_jspx_th_s_005fsubmit_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fonclick_005fname_005fid_005fcssClass_005faction_005fnobody.reuse(_jspx_th_s_005fsubmit_005f2);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f1 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(89,55) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f1.setAction("position_list");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(89,55) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f1.setNamespace("/sys");
    int _jspx_eval_s_005furl_005f1 = _jspx_th_s_005furl_005f1.doStartTag();
    if (_jspx_th_s_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(90,24) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("message");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005faction_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:action
    org.apache.struts2.views.jsp.ActionTag _jspx_th_s_005faction_005f2 = (org.apache.struts2.views.jsp.ActionTag) _005fjspx_005ftagPool_005fs_005faction_0026_005fnamespace_005fname_005fexecuteResult_005fnobody.get(org.apache.struts2.views.jsp.ActionTag.class);
    _jspx_th_s_005faction_005f2.setPageContext(_jspx_page_context);
    _jspx_th_s_005faction_005f2.setParent(null);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(96,0) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005faction_005f2.setName("ref_foot");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(96,0) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005faction_005f2.setNamespace("/manager");
    // /WEB-INF/jsp/sys/PositionEdit.jsp(96,0) name = executeResult type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005faction_005f2.setExecuteResult(true);
    int _jspx_eval_s_005faction_005f2 = _jspx_th_s_005faction_005f2.doStartTag();
    if (_jspx_th_s_005faction_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005faction_0026_005fnamespace_005fname_005fexecuteResult_005fnobody.reuse(_jspx_th_s_005faction_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005faction_0026_005fnamespace_005fname_005fexecuteResult_005fnobody.reuse(_jspx_th_s_005faction_005f2);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f2 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f2.setParent(null);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(99,36) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f2.setValue("/include/dtree/dtree.js");
    int _jspx_eval_s_005furl_005f2 = _jspx_th_s_005furl_005f2.doStartTag();
    if (_jspx_th_s_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f3 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f3.setParent(null);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(107,27) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f3.setValue("/common_ajax/json_ajax");
    int _jspx_eval_s_005furl_005f3 = _jspx_th_s_005furl_005f3.doStartTag();
    if (_jspx_th_s_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f4 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f4.setParent(null);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(146,27) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f4.setValue("/common_ajax/json_ajax");
    int _jspx_eval_s_005furl_005f4 = _jspx_th_s_005furl_005f4.doStartTag();
    if (_jspx_th_s_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f5 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f5.setParent(null);
    // /WEB-INF/jsp/sys/PositionEdit.jsp(252,27) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f5.setValue("/common_ajax/json_ajax");
    int _jspx_eval_s_005furl_005f5 = _jspx_th_s_005furl_005f5.doStartTag();
    if (_jspx_th_s_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f5);
    return false;
  }
}
